<?php
define('C_FICHIER_XML_INITIAL','tmp/analyseEco.xml');
define('C_SESSION_XML_INITIAL','DebutXml');
define('C_SESSION_INFOS_DOSSIER','dossier');
define('C_SESSION_TABLEAU_FLUX','Flux');
define('C_SESSION_SOLDES_INTERMEDIAIRES','SolidinterXml');
define('C_SESSION_RATIOS','Ratios');
define('C_SESSION_BILAN_COMPARATIF','BilanXml');
define('C_SESSION_TABLEAU_FINANCEMENT','Ecorche');
define('C_SESSION_FAIRE_VALOIR','faire_valoir');
define('C_SESSION_STOCKS','stocks');
define('C_SESSION_ASSOLEMENT','assolement');
define('C_SESSION_MAIN_OEUVRE_CALCUL','main_oeuvre_calcul');
define('C_SESSION_ACTIVITE_GLOBALE','activite_globales');
define('C_SESSION_CHARGES_GLOBALES','charges_globales');
define('C_SESSION_MARGE_BRUTE_CALC','marge_brute_calc');
define('C_SESSION_MARGE_BRUTE','marge_brute');
define('C_SESSION_MARGE_PRODUCTION','production');

define('C_SESSION_MARGE_NETTE','marge_nette');
define('C_SESSION_COMMENTAIRE_FINAL','commentaire_final');
define('C_SESSION_INFOS_DOSSIER_EPICEA','infos_epicea');
?>